import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from '../../styles/main.module.css';
import sacoles from "@/utils/sacoles";
import Produto from "@/components/Produto";

type Props = {
    title: string;
    sabor: string;
    gourmet: string | undefined;
}

const inter = Inter({ subsets: ["latin"] });

export default function ProdList({ title, sabor, gourmet }: Props) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {gourmet != "" ?
                    <div className={styles.prodArea}>
                        {sacoles.map((item, index) => (
                            <>
                                {item.gourmet == gourmet ?
                                    <a href={`/produto/${index}`}>
                                        <Produto name={item.name} img={item.img} gourmet={item.gourmet} desc={item.desc} price={item.price} />
                                    </a>
                                    :
                                    ''
                                }
                            </>
                        ))}
                    </div>
                    :
                    ''
                }
                {gourmet == "y" || gourmet == "n" ?
                    ''
                    :
                    <div className={styles.prodArea}>
                        {sacoles.map((item, index) => (
                            <>
                                {item.sabor == sabor ?
                                    <a href={`/produto/${index}`}>
                                        <Produto name={item.name} img={item.img} gourmet={item.gourmet} desc={item.desc} price={item.price} />
                                    </a>
                                    :
                                    ''
                                }
                            </>
                        ))}
                    </div>
                }
            </main>
        </>
    );
}
