import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from '../styles/main.module.css';
import sacoles from "@/utils/sacoles";
import Produto from "@/components/Produto";
import Banner from "@/components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sacolés</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner />
        <div className={styles.prodArea}>
          {sacoles.map((item, index) => (
            <a href={`/produto/${index}`}>
              <Produto name={item.name} img={item.img} gourmet={item.gourmet} desc={item.desc} price={item.price} />
            </a>
          ))}
        </div>
      </main>
    </>
  );
}
